---
- hosts: cluster
  become: yes
  roles:
    - { role: cluster_packages, tags: [ 'prerequisite' ] }
    - { role: cluster_services, tags: [ 'prerequisite' ] }
#    - { role: cluster_scripts, tags: [ 'prerequisite' ] }
