---
- name: Ensure SELinux is set to disabled mode
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
  tags: prerequisite

- name: Create file aws.sh
  copy:
    dest: /etc/profile.d/aws.sh
    content: |
      export PATH=$PATH:/usr/local/bin
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Make sure haproxy is stopped and disabled
  systemd:
    name: haproxy
    enabled: no
    state: stopped
  tags: prerequisite

- name: Make sure keepalived is stopped and disabled
  systemd:
    name: keepalived
    enabled: no
    state: stopped
  tags: prerequisite

- name: Reloading daemons
  command: systemctl daemon-reload
  tags: prerequisite
