---
- name: Ensure SELinux is set to disabled mode for Centos
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled
  when: (ansible_facts['distribution'] == "CentOS")
  tags: prerequisite

- name: Create file aws.sh
  copy:
    dest: /etc/profile.d/aws.sh
    content: |
      export PATH=$PATH:/usr/local/bin
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Make sure haproxy is stopped and disabled
  systemd:
    name: haproxy
    enabled: no
    state: stopped
  tags: prerequisite

- name: Make sure keepalived is stopped and disabled
  systemd:
    name: keepalived
    enabled: no
    state: stopped
  tags: prerequisite

- name: Create file failover.sh
  become: true
  template:
    src: failover.j2
    dest: /etc/keepalived/failover.sh
    owner: root
    group: root
    mode: 0700
  tags: configuration

- name: Create file checkHaproxy.sh
  become: true
  template:
    src: checkHaproxy.j2
    dest: /etc/keepalived/checkHaproxy.sh
    owner: root
    group: root
    mode: 0700
  tags: configuration

- name: Reloading daemons
  command: systemctl daemon-reload
  tags: prerequisite
