---
- name: Upgrade all packages to the latest version
  yum:
    name: '*'
    state: latest
  when: (ansible_facts['distribution'] == "CentOS")
  tags: prerequisite

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  when: (ansible_facts['distribution'] == "Debian")
  tags: prerequisite

- name: Install unzip server packages
  yum:
    name: unzip
    state: present
  when: (ansible_facts['distribution'] == "CentOS")
  register: unzipinstalled
  tags: prerequisite

- name: Install unzip server packages
  apt:
    name: unzip
    state: latest
  when: (ansible_facts['distribution'] == "Debian")
  register: unzipinstalled
  tags: prerequisite

- name: Unarchive awscliv2.zip in /root
  unarchive:
    src: /home/centos/ansible-playbooks/awscliv2.zip
    dest: /root
    owner: root
    group: root
    mode: '0755'
  when: unzipinstalled is succeeded
  register: unarchived
  tags: prerequisite

- name: Check if /usr/local/aws-cli exist - Exit if not
  stat:
    path: /usr/local/aws-cli
  when: unarchived is succeeded
  register: foundedDir
  tags: prerequisite

- name: Thinking to do
  debug:
    msg: "Directory exist. Skipping installation"
  when: foundedDir.stat.isdir is defined
  tags: prerequisite

- name: Installing code
  shell: /root/aws/install
  when: foundedDir.stat.isdir is not defined
  become: yes
  tags: prerequisite

- name: Install bash-completion
  yum:
    name: bash-completion-2.1-6.el7.noarch
    state: present
  when: (ansible_facts['distribution'] == "CentOS")
  tags: prerequisite

- name: Install bash-completion
  apt:
    name: bash-completion
    state: latest
  when: (ansible_facts['distribution'] == "Debian")
  tags: prerequisite

- name: Install haproxy
  yum:
    name: haproxy
    state: present
  when: (ansible_facts['distribution'] == "CentOS")
  tags: prerequisite

- name: Install haproxy
  apt:
    name: haproxy
    state: latest
  when: (ansible_facts['distribution'] == "Debian")
  tags: prerequisite

- name: Install keepalived
  yum:
    name: keepalived.x86_64
    state: present
  when: (ansible_facts['distribution'] == "CentOS")
  tags: prerequisite

- name: Install keepalived
  apt:
    name: keepalived
    state: latest
  when: (ansible_facts['distribution'] == "Debian")
  tags: prerequisite

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  when: (ansible_facts['distribution'] == "CentOS")
  tags: prerequisite

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  when: (ansible_facts['distribution'] == "Debian")
  tags: prerequisite
