---
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: prerequisite

- name: Install unzip server packages
  yum:
    name: unzip
    state: present
  tags: prerequisite

- name: Unarchive awscliv2.zip in /root
  unarchive:
    src: /home/centos/ansible-playbooks/awscliv2.zip
    dest: /root
    owner: root
    group: root
    mode: '0755'
  tags: prerequisite

- name: Check if /usr/local/aws-cli exist - Exit if not
  stat:
    path: /usr/local/aws-cli
  register: foundedDir
  tags: prerequisite

- name: Thinking to do
  debug:
    msg: "Directory exist. Skipping installation"
  when: foundedDir.stat.isdir is defined
  tags: prerequisite

- name: Installing code
  shell: /root/aws/install
  when: foundedDir.stat.isdir is not defined
  become: yes
  tags: prerequisite

- name: Install bash-completion
  yum:
    name: bash-completion-2.1-6.el7.noarch
    state: present
  tags: prerequisite

- name: Install haproxy
  yum:
    name: haproxy
    state: present
  tags: prerequisite

- name: Install keepalived
  yum:
    name: keepalived.x86_64
    state: present
  tags: prerequisite

- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  tags: prerequisite
